### ISSUE TITLE
Replace gunicorn by uwsgi

### ISSUE THREAD

**Issue by yohanboniface** [ideastube/ideastube#161]
It's packaged in Debian with an init script, so we don't need to manage a custom one.

**Comment by fheslouin** [comment]
I'm using uwsgi on ARM and it's working pretty well ! Do you plan to migrate from gunicorn to uwsgi ?

**Comment by yohanboniface** [comment]
Yes, that's the plan :)

**Comment by yohanboniface** [comment]
@fheslouin needs love and tests ;)
