### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by yohanboniface** [ideastube/ideastube#167]
As discussed, "ideasbox" is now both the name of the server and of the whole media kit that includes it (and many other things). The scope of the server is to be used stand-alone, among other in the Koombook project. So, to help distinguish what is what, we think the server must have a separate name than the Ideasbox project.

My own suggestion is "ideasbook", so it's close to the current one, but also distinct.

@fheslouin what was the suggestions collected during the workshop?

I'd like to make this change this month, before we deliver the first koombooks and we send new servers on the wild.

**Comment by barbayellow** [comment]
We were discussing about this today. It seems that the idea of this software being a "server" is missing. Therefore, we could try "LibraryServer". It is very different from the actual one, but is advantageously obvious. And, this software will be used to handle books, documents, videos... Just as a... library !

**Comment by yohanboniface** [comment]
ideaserver? :)

**Comment by barbayellow** [comment]
+1 for "ideaserver".

**Comment by fheslouin** [comment]
Perfect !

**Comment by kelson42** [comment]
brainbox

**Comment by barbayellow** [comment]
Ideaserver seems to be the most appreciated name at BSF. The project will be presented at the event 'Django Carrots' next Monday. It could help to use the definitive name of the project for this presentation. So are we fine with "ideaserver" ?

**Comment by yohanboniface** [comment]
Fine for me.

I can make the change this week-end in the code if you give me the green light :)

**Comment by barbayellow** [comment]
Let's do it !

**Comment by yohanboniface** [comment]
On a second thought: maybe better to do it *after* the pyconfr sprint? Such huge transversal change may have side unexpected effects I could miss, and that would be bad to make people lose time on this during the sprint. What do you think?

**Comment by barbayellow** [comment]
No rush. Let's wait. I'll tell to the sprinters that the project will have a new name in a few days.

**Comment by yohanboniface** [comment]
I'm about to rename and get hit by the last minute doubt: ideaserver or ideasserver? I wonder if this is not a bit error prone :/

So, other last minute suggestions: ideashost, ideasnet, ideastool, ideaspack, ideascase, ideascube, ideastube, ideaspipe, ideasbin, ideascore, gistbox, ideaslive, ideasbook

I like ideascube or ideastube :)

@barbayellow I let you cut this out :)

Sorry for those hesitations, but I'd prefer not to rename twice ;)

**Comment by barbayellow** [comment]
Ideastube definitely. We could have tried "ideas-server" but ideastube describes really what this software is meant to.

**Comment by yohanboniface** [comment]
\o/

(Note: python can't have any '-' in a module name, so `ideas-serever` can't work :/ )

**Comment by yohanboniface** [comment]
Todo in Mapoon and Azarq servers:

- create a backup
- make sure you have created a backup
- download the backup you have created, *just in case*
- install the ideasbox 0.3.3 Debian package, to be sure migrations are up to date with before renaming
- run the dbshell `sudo ideasbox dbshell`
- rename the user table `ALTER TABLE ideasbox_idbuser RENAME TO ideastube_user;`
- sudo mv /var/ideasbox /var/ideastube
- sudo mv /etc/defaults/ideasbox /etc/defaults/ideastube
- install ideastube 0.1.0 package
- fake migrations: `sudo ideastube migrate --fake`
- install last ideastube package

**Comment by yohanboniface** [comment]
Done!
Now to pass on on third party services (Transifex, Github organisation, Travis…). I'll do that tomorrow, so we have this night to change our mind about the new name, or it will be too late ;)
(I had myself a small tear about `ideascube` :p )
