### ISSUE TITLE
Add breadcrum navigation in library, mediacenter

### ISSUE THREAD

**Issue by fheslouin** [ideastube/ideastube#186]
It would be nice to have a breadcrum navigation link to navigate within the website

ex: Homepage -> media center -> image 
      Homepage -> library -> book

When I'm clicking on an image within the media center, there is no way to get back to the media center to show all medias. The only way currently is to click on the back button in my web browser.

**Comment by yohanboniface** [comment]
> When I'm clicking on an image within the media center, there is no way to get back to the media 
> center to show all medias. 

Ah, damn, side effect of removing the header!

**Comment by fheslouin** [comment]
Indeed ! what would be the easiest option ?
