### ISSUE TITLE
Make install install package instead of requirements.txt

### ISSUE THREAD

**Issue by fheslouin** [ideastube/ideastube#189]
I don't know if it has been done in purpose, but the make install command try to install the package in ideastube/build/* instead of installing requirements.txt

**Comment by yohanboniface** [comment]
Use `make devinstall` for local development.

**Comment by yohanboniface** [comment]
Or `make build` then `make install` for deb install.

**Comment by yohanboniface** [comment]
Renamed in `make develop`, sounds less confusing to me.

**Comment by fheslouin** [comment]
+1 make develop

Ok all good, make develop will install requirements.txt anyway
